### ISSUE TITLE
syntax error when executing letsencrypt.sh

### ISSUE THREAD

**Issue by n1mh** [kappataumu/letsencrypt-cloudflare-hook#15]
hi!

When I try to generate the certificates, after following carefully all the points in the readme file, I get this error:

```
# ./letsencrypt.sh -c -d mydomain.net -t dns-01 -k 'hooks/cloudflare/hook.py'
#
# !! WARNING !! No main config file found, using default config!
#
Processing debianhackers.net
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mydomain.net...
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 14, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
```

I've been trying the error unsuccessfully.

Any idea what's going on?

thanks!

**Comment by n1mh** [comment]
Hi again! 

let me answer myself. I needed dnspython on pip to avoid this error.

`pip install dnspython`

I suppose requeriments should be updated.

regards.

**Comment by kappataumu** [comment]
Hello @n1mh! This seems like a common issue (same as #12 and #13), even though the requirements for Python 3 and Python 2 are correctly making a distinction between `dnspython3` and `dnspython`.

Did you by any chance install the Python 3 requirements before realizing you had to use a different requirements file for Python 2? So that i can make it more prominent in the readme file.
