### ISSUE TITLE
variables not read from config file

### ISSUE THREAD

**Issue by ctramnitz** [kappataumu/letsencrypt-cloudflare-hook#24]
I cannot see how the CF_ variables are read from the config file. Dehydrated doesn't seem to do this (anymore?): "BASEDIR and WELLKNOWN variables are exported and can be used in an external program". As a result I'm running into the error message "Unable to locate Cloudflare credentials in environment" although they are in the config file.

**Comment by kappataumu** [comment]
Hello, can you verify that your config file is simply named `config` and placed inside the `dehydrated` directory?

**Comment by ctramnitz** [comment]
The config file is at /etc/dehydrated/config and I can confirm that other entries in the config file (such as executing the hook in the first place) take effect. Looking at dehydrated itself only a few variables are exported:
```
# Export some environment variables to be used in hook script 
export WELLKNOWN BASEDIR CERTDIR CONFIG

```
So I can really not see how any CF_ variables would make it into the hook.

**Comment by kappataumu** [comment]
The `config` file is just a Bash script which is sourced by `dehydrated` (take a look [here](https://github.com/lukas2511/dehydrated/blob/a13e41036381a76de1e77a6ddd3d30170d445d6d/dehydrated#L137)). So we piggyback on that to run arbitrary Bash code when `dehydrated` starts.

This means that you need to `export` these variables yourself to the environment, in your `config` file. It should look like something like this:

```bash
# This is just Bash
export CF_EMAIL=user@example.com
export CF_KEY=K9uX2HyUjeWg5AhAb
export CF_DEBUG=true
echo 'This will be echoed back to you when dehydrated runs'
```

Can you verify that the above works?

The [other entries](https://github.com/lukas2511/dehydrated/blob/a13e41036381a76de1e77a6ddd3d30170d445d6d/docs/examples/config) are initializing variables which are referenced directly by, and are local to, the Bash script sourcing the `config` file (in this case `dehydrated`). This is why, as you noted, `dehydrated` explicitly exports some of them, so that hooks can see them.

**Comment by ctramnitz** [comment]
You are right, I missed the "export" bit, when putting this into the config, all works fine with it.

Sorry for the confusion.

**Comment by kappataumu** [comment]
No worries, glad I could help.
